"""Broad Summer 2027 first-world horizon — companies + universities.

NOT limited to any LinkedIn “5 opportunities” list. Inclusion rules:
  • Destination: OECD / advanced economy (US, CA, UK, EU/EEA/CH, SG, JP, AU, NZ, KR, …)
  • Relevance: SWE / systems / backend / ML-eng / research coding (Ojas resume)
  • Pay: must be paid or fully stipended at a livable level (see pay_band)

pay_band:
  high     — top tech / quant / strong bank tech intern pay
  solid    — clearly paid SWE / research fellowship covering living costs
  research — university stipend (acceptable if fully funded / CHF·CAD·SGD class)
  exclude  — unpaid, volunteer, civil-society, or token pay (kept out of default radar)
"""

from __future__ import annotations

from international.models import Opportunity

# Extend model usage: notes may mention pay_band; we also filter via fit_tags containing pay:*
# Prefer fit_tags including "paid-high" | "paid-solid" | "paid-research"


def _o(**kwargs) -> Opportunity:
	return Opportunity(**kwargs)


OPPORTUNITIES: list[Opportunity] = [
	# ═══════════════════════════════════════════════════════════════════════
	# UNIVERSITY / LAB — paid research & summer fellowships
	# ═══════════════════════════════════════════════════════════════════════
	_o(
		id="cern-summer",
		name="CERN Summer Student Programme",
		org="CERN",
		country="Switzerland",
		region="CH",
		duration="8–13 weeks",
		who_can_apply="CS/Physics/Eng/Math undergrads with ≥6 semesters by EU summer.",
		cost="Fully funded",
		stipend="~90+ CHF/day subsistence + travel (cycle-dependent)",
		typical_deadline_window="Watch Nov→Jan before summer",
		url="https://careers.cern/summer",
		fit_tags=("systems", "cs", "research", "paid-research"),
		visa_note="CERN invitation docs for Switzerland.",
		priority=1,
		status="watch",
		notes="Strong systems/CP fit.",
	),
	_o(
		id="eth-ssrf",
		name="ETH Student Summer Research Fellowship",
		org="ETH Zurich",
		country="Switzerland",
		region="CH",
		duration="~2 months",
		who_can_apply="3rd-year Bachelor or Master in CS / closely related.",
		cost="Fully funded",
		stipend="~CHF 4000 living (historical)",
		typical_deadline_window="Watch Oct→Dec prior year",
		url="https://inf.ethz.ch/studies/summer-research-fellowship.html",
		fit_tags=("cs", "research", "systems", "ml", "paid-research"),
		visa_note="Swiss short-stay via ETH.",
		priority=1,
		status="watch",
	),
	_o(
		id="epfl-intern",
		name="EPFL Lab / Summer Internships",
		org="EPFL",
		country="Switzerland",
		region="CH",
		duration="2–3 months",
		who_can_apply="Strong CS/EE; many labs pay guest students.",
		cost="Lab-stipended when offered",
		stipend="Lab-dependent (target paid offers only)",
		typical_deadline_window="PI outreach from autumn prior year",
		url="https://www.epfl.ch/education/internship/",
		fit_tags=("cs", "research", "systems", "paid-research"),
		visa_note="Swiss internship via host lab.",
		priority=2,
		status="watch",
	),
	_o(
		id="mitacs-globalink",
		name="Mitacs Globalink Research Internship",
		org="Mitacs",
		country="Canada",
		region="CA",
		duration="12 weeks",
		who_can_apply="Undergrads from partner countries (India typically eligible).",
		cost="Fully funded package",
		stipend="Mitacs stipend + housing/flight support (historical)",
		typical_deadline_window="Usually Aug→Nov prior year",
		url="https://www.mitacs.ca/en/programs/globalink/globalink-research-internship",
		fit_tags=("research", "cs", "ml", "india-eligible", "paid-research"),
		visa_note="Canada via Mitacs invitation.",
		priority=1,
		status="watch",
	),
	_o(
		id="astar-singapore",
		name="A*STAR Student Programmes / Research Attachment",
		org="A*STAR",
		country="Singapore",
		region="SG",
		duration="2–6 months",
		who_can_apply="STEM undergrads; Singapore is accessible for Indian students.",
		cost="Typically stipended",
		stipend="A*STAR rates (livable SGD)",
		typical_deadline_window="Multiple cycles — watch continuously",
		url="https://www.a-star.edu.sg/Student-Programmes",
		fit_tags=("research", "cs", "ml", "india-friendly", "paid-solid"),
		visa_note="Training / misc. work pass via A*STAR.",
		priority=1,
		status="watch",
	),
	_o(
		id="daad-rise",
		name="DAAD RISE Germany (when eligible)",
		org="DAAD",
		country="Germany",
		region="EU",
		duration="~10–12 weeks",
		who_can_apply="STEM undergrads; check current nationality windows.",
		cost="DAAD-funded when selected",
		stipend="Monthly DAAD stipend",
		typical_deadline_window="Usually autumn prior year",
		url="https://www.daad.de/rise/en/",
		fit_tags=("research", "cs", "engineering", "paid-research"),
		visa_note="German internship residence.",
		priority=2,
		status="watch",
	),
	_o(
		id="mpi-guest",
		name="Max Planck Institute Guest Student / Intern",
		org="Max Planck Society",
		country="Germany",
		region="EU",
		duration="2–6 months",
		who_can_apply="Strong STEM; apply per MPI (informatics, software systems, IS).",
		cost="Often institute stipend",
		stipend="Institute-dependent — only pursue paid offers",
		typical_deadline_window="Rolling PI outreach",
		url="https://www.mpg.de/en",
		fit_tags=("research", "cs", "systems", "paid-research"),
		visa_note="German research visit via MPI.",
		priority=2,
		status="watch",
	),
	_o(
		id="ntu-nusc-urop",
		name="NUS / NTU Research Internships (Singapore)",
		org="NUS / NTU",
		country="Singapore",
		region="SG",
		duration="Summer / semester",
		who_can_apply="Strong CS/AI undergrads; many labs pay or provide allowance.",
		cost="Often allowance / stipend",
		stipend="Lab-dependent (target paid)",
		typical_deadline_window="Watch faculty pages from late prior year",
		url="https://www.nus.edu.sg/",
		fit_tags=("research", "cs", "ml", "india-friendly", "paid-research"),
		visa_note="Singapore training pass via host uni.",
		priority=2,
		status="watch",
	),
	_o(
		id="ucl-imperial-urop",
		name="UCL / Imperial / Oxbridge summer research (paid schemes)",
		org="UK Russell Group labs",
		country="United Kingdom",
		region="UK",
		duration="6–12 weeks",
		who_can_apply="Strong CS; prefer UROP / EPSRC / departmental paid schemes.",
		cost="Prefer paid UROP only",
		stipend="UK research internship rates when funded",
		typical_deadline_window="Jan→Mar typical for summer",
		url="https://www.imperial.ac.uk/engineering/departments/computing/",
		fit_tags=("research", "cs", "paid-research"),
		visa_note="UK Temporary Worker / visitor rules via host.",
		priority=2,
		status="watch",
		notes="Skip unpaid ‘volunteer research’.",
	),
	_o(
		id="cmu-ri-intern",
		name="CMU / US R1 lab summer research (paid RA)",
		org="US research universities",
		country="USA",
		region="US",
		duration="8–12 weeks",
		who_can_apply="Strong CS; paid RA/REU-like via professor funding.",
		cost="Paid RA preferred",
		stipend="US RA / REU-class stipend",
		typical_deadline_window="Email PIs Sep→Feb",
		url="https://www.cs.cmu.edu/",
		fit_tags=("research", "cs", "systems", "ml", "paid-research"),
		visa_note="J-1 common for paid research visits.",
		priority=2,
		status="watch",
	),
	# ═══════════════════════════════════════════════════════════════════════
	# BIG TECH — paid SWE internships (multi-hub first world)
	# ═══════════════════════════════════════════════════════════════════════
	_o(
		id="google-swe",
		name="Google Software Engineering Intern",
		org="Google",
		country="USA / UK / EU / CA / SG hubs",
		region="US",
		duration="12–14 weeks",
		who_can_apply="CS-adjacent undergrads returning to school after intern.",
		cost="Paid",
		stipend="Top-tier SWE intern pay + housing support (location-dependent)",
		typical_deadline_window="Often opens mid-year prior for next summer (rolling)",
		url="https://careers.google.com/students/",
		fit_tags=("swe", "systems", "cp", "paid-high"),
		visa_note="Prefer UK/IE/EU/SG/CA offices if US auth is hard.",
		priority=1,
		status="watch",
	),
	_o(
		id="microsoft-swe",
		name="Microsoft Software Engineering / Explore Intern",
		org="Microsoft",
		country="USA / UK / EU / CA",
		region="US",
		duration="12 weeks",
		who_can_apply="CS/adjacent; Explore + SWE tracks.",
		cost="Paid",
		stipend="Competitive + relocation often",
		typical_deadline_window="Watch mid–late year prior",
		url="https://careers.microsoft.com/students/",
		fit_tags=("swe", "systems", "cloud", "paid-high"),
		visa_note="Office-dependent sponsorship.",
		priority=1,
		status="watch",
	),
	_o(
		id="meta-swe",
		name="Meta Software Engineer Intern",
		org="Meta",
		country="USA / UK / EU",
		region="US",
		duration="12 weeks",
		who_can_apply="Strong DSA/CS undergrads.",
		cost="Paid",
		stipend="Top-tier",
		typical_deadline_window="Watch metacareers students section",
		url="https://www.metacareers.com/careerprograms/students",
		fit_tags=("swe", "cp", "systems", "paid-high"),
		visa_note="London/Dublin often more feasible than US.",
		priority=1,
		status="watch",
	),
	_o(
		id="amazon-sde",
		name="Amazon SDE Intern",
		org="Amazon",
		country="USA / UK / EU / CA",
		region="US",
		duration="12 weeks",
		who_can_apply="CS/adjacent.",
		cost="Paid",
		stipend="Competitive",
		typical_deadline_window="Rolling",
		url="https://www.amazon.jobs/en/teams/internships-for-students",
		fit_tags=("swe", "backend", "systems", "paid-high"),
		visa_note="UK/DE/IE hubs often better for Indian students.",
		priority=1,
		status="watch",
	),
	_o(
		id="apple-swe",
		name="Apple Software Internships",
		org="Apple",
		country="USA / UK / Ireland / EU",
		region="US",
		duration="~12 weeks",
		who_can_apply="Strong CS.",
		cost="Paid",
		stipend="Top-tier",
		typical_deadline_window="Watch jobs.apple.com/students",
		url="https://www.apple.com/careers/us/students.html",
		fit_tags=("swe", "systems", "paid-high"),
		visa_note="Cork/London sometimes relevant.",
		priority=1,
		status="watch",
	),
	_o(
		id="nvidia-swe",
		name="NVIDIA Software / Systems Intern",
		org="NVIDIA",
		country="USA / UK / EU / CA",
		region="US",
		duration="~12 weeks",
		who_can_apply="CS/EE; systems, CUDA, infra interest.",
		cost="Paid",
		stipend="High",
		typical_deadline_window="Watch nvidia.com/careers",
		url="https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/",
		fit_tags=("swe", "systems", "ml", "paid-high"),
		visa_note="Office-dependent.",
		priority=1,
		status="watch",
	),
	_o(
		id="openai-anthropic",
		name="OpenAI / Anthropic Internships (when posted)",
		org="OpenAI / Anthropic",
		country="USA / UK",
		region="US",
		duration="Summer / flexible",
		who_can_apply="Exceptional CS/ML; highly selective.",
		cost="Paid",
		stipend="Top-of-market",
		typical_deadline_window="Watch careers pages continuously",
		url="https://openai.com/careers/",
		fit_tags=("swe", "ml", "systems", "paid-high"),
		visa_note="US-heavy; UK postings when available.",
		priority=2,
		status="watch",
	),
	_o(
		id="deepmind",
		name="Google DeepMind Internship",
		org="DeepMind",
		country="United Kingdom",
		region="UK",
		duration="12–20 weeks",
		who_can_apply="Strong ML/CS.",
		cost="Paid",
		stipend="Competitive UK research/eng",
		typical_deadline_window="Often Fall prior year",
		url="https://deepmind.google/careers/",
		fit_tags=("ml", "research", "cs", "paid-high"),
		visa_note="UK sponsorship via DeepMind.",
		priority=1,
		status="watch",
	),
	# ═══════════════════════════════════════════════════════════════════════
	# FINTECH / PAYMENTS / PLATFORMS — paid
	# ═══════════════════════════════════════════════════════════════════════
	_o(
		id="stripe",
		name="Stripe Software Engineering Intern",
		org="Stripe",
		country="Ireland / USA / EU",
		region="EU",
		duration="~12 weeks",
		who_can_apply="Strong SWE undergrads; Dublin hub common.",
		cost="Paid",
		stipend="Competitive",
		typical_deadline_window="Watch stripe.com/jobs",
		url="https://stripe.com/jobs/listing?query=intern",
		fit_tags=("swe", "backend", "systems", "paid-high"),
		visa_note="Irish hosting often used.",
		priority=1,
		status="watch",
		notes="Matches API/production work on resume.",
	),
	_o(
		id="revolut",
		name="Revolut Software Engineer Internship Programme",
		org="Revolut",
		country="UK / EU hubs (London, Krakow, Lisbon, …)",
		region="EU",
		duration="8–10 weeks paid",
		who_can_apply="Penultimate CS/math/physics; international applicants; visa/travel/housing support often advertised.",
		cost="Paid + relocation support (conditions apply)",
		stipend="Solid EU tech intern pay (location-dependent)",
		typical_deadline_window="For Summer 2027: apps often open ~May 2026 onward",
		url="https://www.revolut.com/careers/",
		fit_tags=("swe", "backend", "fintech", "india-friendly", "paid-solid"),
		visa_note="Revolut markets visa assistance for several hubs.",
		priority=1,
		status="watch",
		notes="Explicit 2027 programme language has appeared on Revolut careers.",
	),
	_o(
		id="adyen",
		name="Adyen Software Engineering Intern",
		org="Adyen",
		country="Netherlands / EU",
		region="EU",
		duration="Summer",
		who_can_apply="CS students; Amsterdam payments infra.",
		cost="Paid",
		stipend="Solid NL tech pay",
		typical_deadline_window="Watch careers.adyen.com",
		url="https://careers.adyen.com/",
		fit_tags=("swe", "backend", "systems", "paid-solid"),
		visa_note="Dutch orientation year / employer sponsorship paths.",
		priority=2,
		status="watch",
	),
	_o(
		id="shopify",
		name="Shopify Software Engineering Intern",
		org="Shopify",
		country="Canada / remote-first (check policy)",
		region="CA",
		duration="Summer",
		who_can_apply="CS undergrads.",
		cost="Paid",
		stipend="Competitive CAD",
		typical_deadline_window="Watch shopify.com/careers",
		url="https://www.shopify.com/careers/internship",
		fit_tags=("swe", "backend", "paid-high"),
		visa_note="Canada work permit via employer when onsite.",
		priority=1,
		status="watch",
	),
	_o(
		id="databricks",
		name="Databricks Software Engineering Intern",
		org="Databricks",
		country="USA / UK / EU",
		region="US",
		duration="~12 weeks",
		who_can_apply="Strong CS; systems/data infra.",
		cost="Paid",
		stipend="High",
		typical_deadline_window="Watch databricks.com/company/careers",
		url="https://www.databricks.com/company/careers",
		fit_tags=("swe", "systems", "data", "paid-high"),
		visa_note="Office-dependent.",
		priority=1,
		status="watch",
	),
	_o(
		id="cloudflare",
		name="Cloudflare Software Engineering Intern",
		org="Cloudflare",
		country="USA / UK / EU / SG",
		region="US",
		duration="Summer",
		who_can_apply="CS; networking/systems interest.",
		cost="Paid",
		stipend="Competitive",
		typical_deadline_window="Watch cloudflare.com/careers",
		url="https://www.cloudflare.com/careers/",
		fit_tags=("swe", "systems", "networks", "paid-high"),
		visa_note="Multi-hub.",
		priority=1,
		status="watch",
	),
	# ═══════════════════════════════════════════════════════════════════════
	# QUANT / TRADING TECH / HEDGE — paid (systems + CP fit)
	# ═══════════════════════════════════════════════════════════════════════
	_o(
		id="deshaw",
		name="D. E. Shaw — Technology / Systems Intern",
		org="D. E. Shaw",
		country="UK / USA",
		region="UK",
		duration="Summer",
		who_can_apply="Strong CS + systems; CP valued.",
		cost="Paid",
		stipend="Very high",
		typical_deadline_window="Campus + deshaw.com/careers",
		url="https://www.deshaw.com/careers/internships",
		fit_tags=("systems", "swe", "cp", "paid-high"),
		visa_note="London sometimes more accessible.",
		priority=1,
		status="watch",
	),
	_o(
		id="janestreet",
		name="Jane Street Internship",
		org="Jane Street",
		country="UK / USA / SG / HK",
		region="UK",
		duration="Summer",
		who_can_apply="Exceptional problem-solvers.",
		cost="Paid",
		stipend="Top-of-market",
		typical_deadline_window="Often early — watch mid prior year",
		url="https://www.janestreet.com/join-jane-street/internships/",
		fit_tags=("cp", "systems", "swe", "paid-high"),
		visa_note="London/Asia hubs.",
		priority=1,
		status="watch",
	),
	_o(
		id="hrt",
		name="Hudson River Trading Intern",
		org="Hudson River Trading",
		country="USA / UK / EU / Asia",
		region="US",
		duration="Summer",
		who_can_apply="Strong CS/math; systems & trading tech.",
		cost="Paid",
		stipend="Top-tier",
		typical_deadline_window="Watch hudsonrivertrading.com/careers",
		url="https://www.hudsonrivertrading.com/careers/",
		fit_tags=("cp", "systems", "swe", "paid-high"),
		visa_note="Multi-office.",
		priority=1,
		status="watch",
	),
	_o(
		id="citadel-securities",
		name="Citadel Securities / Citadel Technology Intern",
		org="Citadel",
		country="USA / UK / EU / Asia",
		region="US",
		duration="Summer",
		who_can_apply="Strong CS/math.",
		cost="Paid",
		stipend="Top-tier",
		typical_deadline_window="Watch citadel.com/careers",
		url="https://www.citadel.com/careers/open-opportunities/",
		fit_tags=("cp", "systems", "swe", "paid-high"),
		visa_note="London/Dublin/Asia options.",
		priority=1,
		status="watch",
	),
	_o(
		id="twosigma",
		name="Two Sigma Internships",
		org="Two Sigma",
		country="USA / UK",
		region="US",
		duration="Summer",
		who_can_apply="CS/math strong.",
		cost="Paid",
		stipend="High",
		typical_deadline_window="Watch twosigma.com/careers",
		url="https://www.twosigma.com/careers/",
		fit_tags=("swe", "systems", "ml", "paid-high"),
		visa_note="Office-dependent.",
		priority=1,
		status="watch",
	),
	_o(
		id="optiver",
		name="Optiver Software / Trading Intern",
		org="Optiver",
		country="NL / USA / AU / Asia",
		region="EU",
		duration="Summer",
		who_can_apply="CS/math; Amsterdam HQ.",
		cost="Paid",
		stipend="High EU/US trading tech",
		typical_deadline_window="Watch optiver.com/working-at-optiver",
		url="https://optiver.com/working-at-optiver/career-opportunities/",
		fit_tags=("cp", "systems", "swe", "paid-high"),
		visa_note="NL/AU hubs often hire internationals.",
		priority=1,
		status="watch",
	),
	_o(
		id="imc",
		name="IMC Trading Internships",
		org="IMC",
		country="NL / USA / Asia / AU",
		region="EU",
		duration="Summer",
		who_can_apply="CS/math.",
		cost="Paid",
		stipend="High",
		typical_deadline_window="Watch imc.com/careers",
		url="https://www.imc.com/us/careers",
		fit_tags=("cp", "swe", "systems", "paid-high"),
		visa_note="Amsterdam + Asia.",
		priority=1,
		status="watch",
	),
	_o(
		id="jump",
		name="Jump Trading Intern",
		org="Jump Trading",
		country="USA / UK / EU / Asia",
		region="US",
		duration="Summer",
		who_can_apply="Strong systems/CP.",
		cost="Paid",
		stipend="Top-tier",
		typical_deadline_window="Watch jumptrading.com/careers",
		url="https://www.jumptrading.com/careers/",
		fit_tags=("systems", "cp", "swe", "paid-high"),
		visa_note="Multi-office.",
		priority=1,
		status="watch",
	),
	# ═══════════════════════════════════════════════════════════════════════
	# BANKS / MARKETS TECH — paid technology internships
	# ═══════════════════════════════════════════════════════════════════════
	_o(
		id="jpmorgan-tech",
		name="J.P. Morgan Software Engineer Summer Internship",
		org="J.P. Morgan",
		country="UK / USA / EU / SG / HK",
		region="UK",
		duration="~10 weeks",
		who_can_apply="Penultimate CS; check right-to-work per office (some UK roles require existing RTW).",
		cost="Paid",
		stipend="Strong bank-tech pro-rata",
		typical_deadline_window="Autumn campus cycles",
		url="https://careers.jpmorgan.com/students",
		fit_tags=("swe", "fintech", "paid-solid"),
		visa_note="Prefer SG/EU offices that sponsor; verify each posting.",
		priority=2,
		status="watch",
	),
	_o(
		id="goldman-tech",
		name="Goldman Sachs Engineering Summer Analyst",
		org="Goldman Sachs",
		country="UK / USA / EU / Asia",
		region="UK",
		duration="Summer",
		who_can_apply="CS/adjacent penultimate.",
		cost="Paid",
		stipend="Strong",
		typical_deadline_window="Early campus deadlines",
		url="https://www.goldmansachs.com/careers/students",
		fit_tags=("swe", "fintech", "paid-solid"),
		visa_note="Office-dependent.",
		priority=2,
		status="watch",
	),
	_o(
		id="barclays-tech-sg",
		name="Barclays Technology Developer Summer Internship",
		org="Barclays",
		country="Singapore / UK / EU",
		region="SG",
		duration="Summer",
		who_can_apply="CS/IT students; SG programme posts for 2027 cohorts.",
		cost="Paid",
		stipend="Solid SG bank-tech",
		typical_deadline_window="Watch search.jobs.barclays",
		url="https://search.jobs.barclays/",
		fit_tags=("swe", "fintech", "india-friendly", "paid-solid"),
		visa_note="Singapore TEP / work pass via bank.",
		priority=1,
		status="watch",
	),
	_o(
		id="bloomberg",
		name="Bloomberg Software Engineering Intern",
		org="Bloomberg",
		country="UK / USA",
		region="UK",
		duration="~10–12 weeks",
		who_can_apply="CS students; London strong for internationals.",
		cost="Paid",
		stipend="Competitive",
		typical_deadline_window="Often autumn prior year",
		url="https://www.bloomberg.com/company/careers/students/",
		fit_tags=("swe", "systems", "cpp", "paid-high"),
		visa_note="UK sponsorship common historically.",
		priority=1,
		status="watch",
	),
	_o(
		id="visa-sg",
		name="Visa Software Engineering Intern (APAC hubs)",
		org="Visa",
		country="Singapore / USA / EU",
		region="SG",
		duration="~12 weeks",
		who_can_apply="CS; check RTW — some SG posts require local RTW.",
		cost="Paid",
		stipend="Solid",
		typical_deadline_window="Watch Visa careers / SmartRecruiters",
		url="https://usa.visa.com/careers/university-recruiting.html",
		fit_tags=("swe", "fintech", "paid-solid"),
		visa_note="Verify sponsorship line on each posting.",
		priority=2,
		status="watch",
	),
	# ═══════════════════════════════════════════════════════════════════════
	# MORE FIRST-WORLD TECH (paid) — horizon breadth
	# ═══════════════════════════════════════════════════════════════════════
	_o(
		id="uber",
		name="Uber Software Engineering Intern",
		org="Uber",
		country="USA / NL / EU",
		region="EU",
		duration="Summer",
		who_can_apply="CS undergrads.",
		cost="Paid",
		stipend="Competitive",
		typical_deadline_window="Watch uber.com/careers",
		url="https://www.uber.com/careers/university/",
		fit_tags=("swe", "backend", "paid-high"),
		visa_note="Amsterdam hub relevant.",
		priority=2,
		status="watch",
	),
	_o(
		id="spotify",
		name="Spotify Engineering Intern",
		org="Spotify",
		country="Sweden / UK / EU / USA",
		region="EU",
		duration="Summer",
		who_can_apply="CS.",
		cost="Paid",
		stipend="Solid EU tech",
		typical_deadline_window="Watch lifeatspotify.com",
		url="https://www.lifeatspotify.com/students",
		fit_tags=("swe", "backend", "paid-solid"),
		visa_note="Stockholm/London.",
		priority=2,
		status="watch",
	),
	_o(
		id="asml",
		name="ASML Software / Engineering Intern",
		org="ASML",
		country="Netherlands",
		region="EU",
		duration="Summer / thesis",
		who_can_apply="CS/EE; systems & software for lithography.",
		cost="Paid",
		stipend="Solid NL engineering",
		typical_deadline_window="Watch asml.com/careers",
		url="https://www.asml.com/en/careers/internships-and-trainees",
		fit_tags=("swe", "systems", "engineering", "paid-solid"),
		visa_note="NL highly open to STEM internationals.",
		priority=2,
		status="watch",
	),
	_o(
		id="sap-eu",
		name="SAP Developer Internships (EU)",
		org="SAP",
		country="Germany / EU",
		region="EU",
		duration="3–6 months common",
		who_can_apply="CS students.",
		cost="Paid",
		stipend="German/EU working-student / intern rates",
		typical_deadline_window="Rolling jobs.sap.com",
		url="https://jobs.sap.com/",
		fit_tags=("swe", "enterprise", "paid-solid"),
		visa_note="German working student / internship permits.",
		priority=2,
		status="watch",
	),
	_o(
		id="booking",
		name="Booking.com Software Engineering Intern",
		org="Booking.com",
		country="Netherlands",
		region="EU",
		duration="Summer",
		who_can_apply="CS.",
		cost="Paid",
		stipend="Solid NL",
		typical_deadline_window="Watch booking.com/careers",
		url="https://careers.booking.com/early-careers/",
		fit_tags=("swe", "backend", "paid-solid"),
		visa_note="Amsterdam.",
		priority=2,
		status="watch",
	),
	_o(
		id="canva",
		name="Canva Software Engineering Intern",
		org="Canva",
		country="Australia / Asia hubs",
		region="AU",
		duration="Summer (AU calendar may differ)",
		who_can_apply="CS.",
		cost="Paid",
		stipend="Competitive AUD",
		typical_deadline_window="Watch canva.com/careers — note AU summer offset",
		url="https://www.canva.com/careers/",
		fit_tags=("swe", "paid-solid"),
		visa_note="Australian temporary activity / student pathways.",
		priority=3,
		status="watch",
		notes="Calendar may not match May–Jul India break.",
	),
	_o(
		id="rakuten-ly",
		name="Rakuten / LINE Yahoo Japan Eng Intern",
		org="Rakuten Group",
		country="Japan",
		region="JP",
		duration="Summer / flexible",
		who_can_apply="CS; some English-friendly teams.",
		cost="Paid when offered",
		stipend="JP eng intern rates",
		typical_deadline_window="Watch rakuten.careers",
		url="https://rakuten.careers/",
		fit_tags=("swe", "paid-solid"),
		visa_note="Japanese designated activities / intern visa.",
		priority=3,
		status="watch",
	),
	# ═══════════════════════════════════════════════════════════════════════
	# MOBILITY (only if paid / grant-backed)
	# ═══════════════════════════════════════════════════════════════════════
	_o(
		id="iaeste",
		name="IAESTE Technical Internships (paid employer placements)",
		org="IAESTE",
		country="Multiple first-world hosts",
		region="EU",
		duration="4–52 weeks",
		who_can_apply="STEM via IAESTE India committee; employer-paid roles only.",
		cost="Employer-paid",
		stipend="Country norms (must be paid technical placement)",
		typical_deadline_window="National committee cycles",
		url="https://iaeste.org/",
		fit_tags=("engineering", "cs", "india-eligible", "paid-solid"),
		visa_note="Host visa via IAESTE docs.",
		priority=2,
		status="watch",
	),
	_o(
		id="erasmus-plus",
		name="Erasmus+ Traineeship (grant-backed, via SVNIT IR)",
		org="Erasmus+",
		country="Europe",
		region="EU",
		duration="2–12 months",
		who_can_apply="Only if SVNIT holds / partners for Erasmus+ — confirm IR office.",
		cost="Grant-supported",
		stipend="Up to ~€1400/mo country rate + host pay if any",
		typical_deadline_window="Campus IR deadlines",
		url="https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/traineeships-abroad-for-students",
		fit_tags=("mobility", "campus-dependent", "paid-research"),
		visa_note="Schengen via grant + host.",
		priority=2,
		status="watch",
		notes="Not cold LinkedIn Mundus spam — go through SVNIT.",
	),
]


PAID_TAGS = frozenset({"paid-high", "paid-solid", "paid-research"})


def all_opportunities() -> list[Opportunity]:
	return list(OPPORTUNITIES)


def paid_only(opps: list[Opportunity] | None = None) -> list[Opportunity]:
	src = opps if opps is not None else OPPORTUNITIES
	return [o for o in src if PAID_TAGS.intersection(o.fit_tags)]


def by_priority(max_priority: int = 2) -> list[Opportunity]:
	return sorted(
		paid_only([o for o in OPPORTUNITIES if o.priority <= max_priority]),
		key=lambda o: (o.priority, o.region, o.name),
	)


def high_fit_for_ojas() -> list[Opportunity]:
	"""Default radar: paid + resume-relevant (SWE/systems/CP/research coding)."""
	wanted = {
		"swe",
		"systems",
		"cs",
		"cp",
		"backend",
		"ml",
		"research",
		"fintech",
		"data",
		"networks",
		"cloud",
		"india-eligible",
		"india-friendly",
	}
	out = []
	for o in paid_only():
		if not wanted.intersection(o.fit_tags):
			continue
		if o.priority >= 3 and "paid-high" not in o.fit_tags:
			continue
		out.append(o)
	return sorted(out, key=lambda o: (o.priority, o.name))


def companies_vs_universities() -> tuple[list[Opportunity], list[Opportunity]]:
	uni_keys = ("research", "cern", "eth", "epfl", "mitacs", "astar", "daad", "mpi", "nus", "ntu", "ucl", "imperial", "cmu")
	unis, cos = [], []
	for o in paid_only():
		blob = f"{o.id} {o.name} {o.org}".lower()
		if any(k in blob for k in uni_keys) or "research" in o.fit_tags and o.priority <= 2 and "swe" not in o.fit_tags:
			# heuristic: research-tagged without swe → uni track; else company if swe/fintech
			if "swe" in o.fit_tags or "fintech" in o.fit_tags or "cp" in o.fit_tags:
				cos.append(o)
			else:
				unis.append(o)
		elif "swe" in o.fit_tags or "fintech" in o.fit_tags or "cp" in o.fit_tags:
			cos.append(o)
		else:
			unis.append(o)
	return unis, cos
